### ISSUE TITLE
FBX 

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#120]

**Comment by BearishSun** [comment]
Could you send me that model? I am unable to reproduce with my test models.

**Comment by christianclavet** [comment]
Thanks! I've sent you a mail with a link to a test scene containing the model to check.

**Comment by BearishSun** [comment]
The incorrect rotation problem is fixed with 39e4033d6dfc1102c33cdd82b0fc3b66d25b3e17. I'll keep the issue open as there are other problems with the animation system I'm still looking into.

**Comment by BearishSun** [comment]
Additional fix regarding invalid animation curves, ab0602fb87d99dfbf855c5b752874870aeaa93e4. This one was causing weirdness with the finger animations on your model. Looking into a few more animation related issues.

**Comment by christianclavet** [comment]
Thanks Marko! I also tried to animate objects with the animation window but failed, only the X axis was animating properly, the 2 other axes were replicating data on other channels. This animation window could prove VERY useful for creating cutscenes! Or even creating small movies in Banshee like Adam ( [https://youtu.be/GXI0l3yqBrA](https://youtu.be/GXI0l3yqBrA) )

**Comment by christianclavet** [comment]
Just rebuilded the application with your latest changes and I can now scrub the animation window and see the character correctly animated! Wow!

I see a small drawing issue when the window is docked: (was there since the beginning)
![report](https://user-images.githubusercontent.com/13395943/34458345-cf6f2056-ed9b-11e7-8568-62084be2f040.JPG)

Still unable to animate an object with the animation windows (using the record button and also pressing the record keyframe). Some axis doesnt work properly, only the X axis seem to work.
